[project]
name = "py-fastapi-project"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "fastapi==0.110.3",
    "httpx>=0.28.1",
    "uvicorn>=0.38.0",
]
[project.scripts]
app = "main:app"